add_rules("plugin.compile_commands.autoupdate", {outputdir ="build" })
set_languages("cxx14")
set_defaultmode("debug")

target("ba-hla")
  set_symbols ("debug")
  set_optimize("none")
  set_kind("binary")
  add_files("source/transport_hla/**.cpp")
  add_includedirs("/home/yonchicy/OpenRTI/include/rti1516")
  add_includedirs("source")
  add_links("/home/yonchicy/OpenRTI/build/lib64/librti1516.so","/home/yonchicy/OpenRTI/build/lib64/libfedtime1516.so","mariadb")
  add_rpathdirs("/home/yonchicy/OpenRTI/build/lib64")
  set_targetdir("$(buildir)")

target("ba-hla-tmp")
  set_symbols ("debug")
  set_optimize("none")
  set_kind("binary")
  add_files("source/ba_hla/**.cpp")
  add_includedirs("/home/yonchicy/OpenRTI/include/rti1516")
  add_includedirs("source")
  add_links("/home/yonchicy/OpenRTI/build/lib64/librti1516.so","/home/yonchicy/OpenRTI/build/lib64/libfedtime1516.so","mariadb")
  add_rpathdirs("/home/yonchicy/OpenRTI/build/lib64")
  set_targetdir("$(buildir)")
